// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDybc-KJjVM69moGSAgSxNXuXWNQQkQv8',
    appId: '1:736987488793:android:d14a338d0dce3c268ec088',
    messagingSenderId: '736987488793',
    projectId: 'artisan2022-b24bd',
    databaseURL: 'https://artisan2022-b24bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'artisan2022-b24bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCObH5SQip7M360LP-FuR0yoT0qfR8ZB0',
    appId: '1:736987488793:ios:0635613afb9a34268ec088',
    messagingSenderId: '736987488793',
    projectId: 'artisan2022-b24bd',
    databaseURL: 'https://artisan2022-b24bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'artisan2022-b24bd.appspot.com',
    iosClientId: '736987488793-4ua1vdlbbie0pm13sloo96i260bnae1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.monArtisanProject',
  );
}
